# Generated by Django 4.2.7 on 2025-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_amenity_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='core_room_city_de8e2a_idx',
        ),
        migrations.RemoveField(
            model_name='room',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='room',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number (Optional)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(help_text='Minimum 50 characters required', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monthly Rent'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['city'], name='core_room_city_a2234f_idx'),
        ),
    ]
