# Generated by Django 5.2.6 on 2025-09-28 15:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_room_core_room_city_de8e2a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your profile photo (max 3MB, JPEG/PNG/WEBP). Required for profile completion.', null=True, upload_to='profile_photos/', validators=[core.models.validate_profile_image_size, core.models.validate_profile_image_format], verbose_name='Profile Photo'),
        ),
    ]
