# Generated by Django 5.1.2 on 2025-10-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_profile_only_eats_zabihah_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person giving feedback", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for follow-up (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("ui_ux", "UI/UX Feedback"),
                            ("general", "General Feedback"),
                            ("praise", "Praise/Positive"),
                        ],
                        default="general",
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the feedback", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Detailed feedback message")),
                (
                    "page_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the page where issue occurred",
                        null=True,
                    ),
                ),
                (
                    "browser_info",
                    models.CharField(
                        blank=True,
                        help_text="Browser and device information",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback has been addressed",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes for tracking resolution",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted feedback (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
