# Generated by Django 5.1.2 on 2025-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Include country code (e.g., +12025551234) - This is the easiest way for people to contact you!",
                max_length=20,
                verbose_name="WhatsApp Number",
            ),
        ),
    ]
